name: Generate Dataset

on:
  workflow_dispatch:

jobs:
  generate_dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'libs/dataset/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Create .env file
        run: echo "GITHUB_TOKENS=${{ secrets.TOKENS }}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r libs/dataset/requirements.txt

      - name: Generate dataset
        run: python generate_dataset.py

      - name: Format dataset to .parquet format
        run: python format_dataset.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dataset-artifacts
          path: |
            issues.db
            github_issues_dataset.parquet
