name: Generate Dataset

on:
  workflow_dispatch:

jobs:
  generate_dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Create .env file
        run: |
          echo "GITHUB_TOKENS=${{ secrets.TOKENS }}" > .env
          # Add other env variables if needed.

      - name: Install main dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r libs/dataset/requirements.txt

      - name: Generate dataset
        run: |
          python generate_dataset.py

      - name: Upload issues.db artifact
        uses: actions/upload-artifact@v3
        with:
          name: issues-db
          path: issues.db
      
      - name: Format Dataset to .parquet format
        run: |
            python format_dataset.py
      
      - name: Upload github_issues_dataset.parquet artifact
        uses: actions/upload-artifact@v3
        with:
          name: github_issues_dataset-parquet
          path: github_issues_dataset.parquet